"""empty message

Revision ID: 160991adb60f
Revises: 527dd0a7c6c8
Create Date: 2024-06-23 17:30:03.294268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160991adb60f'
down_revision = '527dd0a7c6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('background2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('background3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('background4', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('background4')
        batch_op.drop_column('background3')
        batch_op.drop_column('background2')
        batch_op.drop_column('background1')

    # ### end Alembic commands ###
