"""empty message

Revision ID: 4974a4dbc6dd
Revises: d8c5f6da17b9
Create Date: 2024-06-21 17:15:58.329851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4974a4dbc6dd'
down_revision = 'd8c5f6da17b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statement_of_availability', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('statement_of_availability')

    # ### end Alembic commands ###
