"""empty message

Revision ID: 527dd0a7c6c8
Revises: b88224b09cbd
Create Date: 2024-06-23 17:21:39.383695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '527dd0a7c6c8'
down_revision = 'b88224b09cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_availability', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('data_availability', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('code_availability', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('code_availability')
        batch_op.drop_column('data_availability')
        batch_op.drop_column('materials_availability')

    # ### end Alembic commands ###
