"""empty message

Revision ID: 6a3ca218f3ee
Revises: 76b33a29e04c
Create Date: 2024-06-29 01:33:38.376184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3ca218f3ee'
down_revision = '76b33a29e04c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preregistration_e', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('statement_of_availability_e', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('materials_availability_e', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('data_availability_e', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('code_availability_e', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('code_availability_e')
        batch_op.drop_column('data_availability_e')
        batch_op.drop_column('materials_availability_e')
        batch_op.drop_column('statement_of_availability_e')
        batch_op.drop_column('preregistration_e')

    # ### end Alembic commands ###
