"""empty message

Revision ID: 76b33a29e04c
Revises: 6457e4a34390
Create Date: 2024-06-28 21:19:53.264889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b33a29e04c'
down_revision = '6457e4a34390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_access_e', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('general_comment', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('general_comment')
        batch_op.drop_column('open_access_e')

    # ### end Alembic commands ###
