"""empty message

Revision ID: c22b9949c3f5
Revises: 9f7b88e4ae20
Create Date: 2025-01-19 18:51:02.787627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22b9949c3f5'
down_revision = '9f7b88e4ae20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onlinefirst', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('onlinefirst')

    # ### end Alembic commands ###
