"""empty message

Revision ID: d8c5f6da17b9
Revises: 
Create Date: 2024-06-21 14:24:36.400712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c5f6da17b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['short'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('short')

    # ### end Alembic commands ###
